### PR TITLE
Enh #170: Push notifications

### PR DESCRIPTION
**Pull request by felixhahnweilheim**
Temporary solution as suggested by @luke- in https://github.com/humhub/mail/issues/170#issuecomment-1878529606

### CODE REVIEW

**Comment by felixhahnweilheim** [comment]
That's how the mmnotification now looks on Android:



It opens directly the conversation.

From my side the PR is ready to merge.

Let me know if I should rework the notification text.
We could also use the message content.
Maybe like:
```felix test @Test Chat: "Hey everyone, I wanted to ask something abo..."```

Then I would have to know how many characters are allowed.

**Comment by luke-** [comment]
@felixhahnweilheim Thanks looks nice!

@yurabakhtin Can you please review?

**Review by yurabakhtin — APPROVED** [review]

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
@felixhahnweilheim Thank you for the contribution. The text is fine.

**Comment by marc-farre** [comment]
@felixhahnweilheim Thanks very much for your work! This really was a missing feature for the mobile app!

**Pull request merged**
