### PR TITLE
Added the ability to control which groups have access to the mail con…

### PR DESCRIPTION
**Pull request by jeremiahtenbrink**
…troller.

### CODE REVIEW

**Comment by jeremiahtenbrink** [comment]
I added the ability to manage which groups have access to the mail controller. The options for the group show up in the admin section, groups, click edit on a specific group, then click the permissions tab.

**Comment by jeremiahtenbrink** [comment]
Changed some more of the permission to show or not show the send message button on users profiles based on their preferences.

**Comment by Felli** [comment]
@jeremiahtenbrink any news about updating this? I've been wanting to see something like this implemented.

**Comment by luke-** [comment]
@yurabakhtin Thanks for the investigation.

You need to enable Profile Permissions first.
image


Then the permission is available and should work as expected.

I would suggest to close this PR for now.

@jeremiahtenbrink Sorry we got to this so late and it went down before that.

**Pull request closed without merging**
