### PR TITLE
New Design

### PR DESCRIPTION
**Pull request by yurabakhtin**
Issues: https://github.com/humhub/mail/issues/280, https://github.com/humhub/mail/issues/281

### CODE REVIEW

**Comment by luke-** [comment]
@Eladnarlea  I have applied the latest changes to your test environment.

**Comment by yurabakhtin** [comment]
@luke- Can I do all changes realted to new design from https://github.com/humhub/mail/issues/282 in this PR?
Otherwise it will be difficult to merge many PRs with changes in same files like `*.css`.

**Comment by luke-** [comment]
@yurabakhtin Yes, it's also better for testing.

**Comment by Eladnarlea** [comment]
> @Eladnarlea I have applied the latest changes to your test environment.

Thank you,  I will take a look at it :)

**Review by luke- — APPROVED** [review]
Thanks looks good!

**Comment by Eladnarlea** [comment]
@luke- Can we close this?

**Review by luke- — APPROVED** [review]

**Pull request merged**
